#spring:
#  server:
#    port: 8080
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      username: admin
#      password: pass
#      database: test
#      authentication-database: admin
#logging:
#  level:
#    org.springframework.data.mongodb.core.MongoTemplate: DEBUG